# ========== ОСНОВНЫЕ НАСТРОЙКИ ==========
ASSISTANT_NAME = "мия"
ASSISTANT_ALIASES = [
    "мия", "миа", "ми", "мияя", "мию", "мие", "мией",
    "mio", "mia", "miya", "miia", "meeia", "мееиа",
    "миий", "мияй", "мияяя", "миии", "миия", "меня", "Mi", "mi", "мне", 
    "Мне",
    "мbя", "мuя", "миe", "миу", "мио",
]
LANGUAGE = "ru-RU"
VOICE_INDEX = 0

# ========== ГОРЯЧЕЕ СЛОВО (пока не активно) ==========
WAKE_WORD_ENABLED = False
WAKE_WORD_SENSITIVITY = 0.5

# ========== ИИ-МОЗГИ ==========
AI_ENABLED = False
AI_PROVIDER = "openrouter"
AI_API_KEY = "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"
AI_MODEL = "gpt-3.5-turbo"

# ========== ВСЕ ПРОГРАММЫ И ИГРЫ ==========
# Формат: "название_как_говорить": "имя_процесса.exe"
# Если путь — то полный путь, если просто имя — ищет в системе

APPS = {
    # === Браузеры ===
    "браузер": "msedge.exe",
    "гугл хром": "chrome.exe",
    "хром": "chrome.exe",
    "яндекс браузер": "browser.exe",
    "опера": "opera.exe",
    "фаерфокс": "firefox.exe",
    "можилла": "firefox.exe",
    "сафари": "safari.exe",
    "вивальди": "vivaldi.exe",
    "тор браузер": "tor.exe",
    "тор": "tor.exe",
    
    # === Офис ===
    "ворд": "WINWORD.EXE",
    "майкрософт ворд": "WINWORD.EXE",
    "эксель": "EXCEL.EXE",
    "майкрософт эксель": "EXCEL.EXE",
    "пауэр поинт": "POWERPNT.EXE",
    "презентация": "POWERPNT.EXE",
    "аутлук": "OUTLOOK.EXE",
    "почта майкрософт": "OUTLOOK.EXE",
    "вордпад": "write.exe",
    "блокнот": "notepad.exe",
    "заметки": "notepad.exe",
    "калькулятор": "calc.exe",
    "кальк": "calc.exe",
    
    # === Системные ===
    "проводник": "explorer.exe",
    "файлы": "explorer.exe",
    "мой компьютер": "explorer.exe",
    "диспетчер задач": "taskmgr.exe",
    "панель управления": "control.exe",
    "параметры": "ms-settings:",
    "настройки": "ms-settings:",
    "командная строка": "cmd.exe",
    "консоль": "cmd.exe",
    "терминал": "wt.exe",
    "пауэршелл": "powershell.exe",
    "редактор реестра": "regedit.exe",
    "реестр": "regedit.exe",
    "экранная клавиатура": "osk.exe",
    "клавиатура экранная": "osk.exe",
    "лупа": "magnify.exe",
    "ножницы": "SnippingTool.exe",
    "скриншотер": "SnippingTool.exe",
    "подключение к удаленному рабочему столу": "mstsc.exe",
    "чистка диска": "cleanmgr.exe",
    "дефрагментация": "dfrgui.exe",
    "сведения о системе": "msinfo32.exe",
    "монитор ресурсов": "resmon.exe",
    
    # === Графика и дизайн ===
    "паинт": "mspaint.exe",
    "пэинт": "mspaint.exe",
    "фотошоп": "Photoshop.exe",
    "адоб фотошоп": "Photoshop.exe",
    "иллюстратор": "Illustrator.exe",
    "адоб иллюстратор": "Illustrator.exe",
    "корел дро": "CorelDRW.exe",
    "корел": "CorelDRW.exe",
    "блендер": "blender.exe",
    "автокад": "acad.exe",
    "скетчап": "SketchUp.exe",
    "фигма": "Figma.exe",
    "гимп": "gimp-2.10.exe",
    
    # === Видео и аудио ===
    "премьер про": "Adobe Premiere Pro.exe",
    "адоб премьер": "Adobe Premiere Pro.exe",
    "афтер эффектс": "AfterFX.exe",
    "сонь вегас": "vegas140.exe",
    "вегас": "vegas140.exe",
    "давинчи резолв": "Resolve.exe",
    "кап кут": "CapCut.exe",
    "одесити": "audacity.exe",
    "фл студио": "FL64.exe",
    "фл студия": "FL64.exe",
    "аблетон": "Ableton Live 11 Suite.exe",
    
    # === Разработка ===
    "вижуал студио": "devenv.exe",
    "вижуал студио код": "Code.exe",
    "вс код": "Code.exe",
    "пайчарм": "pycharm64.exe",
    "интеллидж": "idea64.exe",
    "андроид студио": "studio64.exe",
    "блокнот плюс плюс": "notepad++.exe",
    "саблайм": "sublime_text.exe",
    "гит": "git-bash.exe",
    "гитхаб десктоп": "GitHubDesktop.exe",
    "постман": "Postman.exe",
    "докер": "Docker Desktop.exe",
    
    # === Мессенджеры ===
    "телеграм": "Telegram.exe",
    "телега": "Telegram.exe",
    "вотсап": "WhatsApp.exe",
    "вайбер": "Viber.exe",
    "дискорд": "Discord.exe",
    "скайп": "Skype.exe",
    "слак": "slack.exe",
    "зум": "Zoom.exe",
    "тимс": "Teams.exe",
    "майкрософт тимс": "Teams.exe",
    
    # === Игры ===
    "стим": "Steam.exe",
    "эпик геймс": "EpicGamesLauncher.exe",
    "эпик": "EpicGamesLauncher.exe",
    "гог": "GOG Galaxy.exe",
    "юбисофт коннект": "UbisoftConnect.exe",
    "ориджин": "Origin.exe",
    "батл нет": "Battle.net.exe",
    "близзард": "Battle.net.exe",
    "майнкрафт": "Minecraft.exe",
    "майн": "Minecraft.exe",
    "гта 5": "GTA5.exe",
    "гта": "GTA5.exe",
    "фортнайт": "FortniteClient-Win64-Shipping.exe",
    "форта": "FortniteClient-Win64-Shipping.exe",
    "ксс": "cs2.exe",
    "кс го": "cs2.exe",
    "контр страйк": "cs2.exe",
    "кс 2": "cs2.exe",
    "дота": "dota2.exe",
    "дота 2": "dota2.exe",
    "валорант": "VALORANT.exe",
    "валорка": "VALORANT.exe",
    "лига легенд": "LeagueClient.exe",
    "лол": "LeagueClient.exe",
    "лига": "LeagueClient.exe",
    "ведьмак": "witcher3.exe",
    "ведьмак 3": "witcher3.exe",
    "скайрим": "SkyrimSE.exe",
    "киберпанк": "Cyberpunk2077.exe",
    "кибер панк": "Cyberpunk2077.exe",
    "пабг": "TslGame.exe",
    "апекс": "r5apex.exe",
    "апекс легендс": "r5apex.exe",
    "овервотч": "Overwatch.exe",
    "овер": "Overwatch.exe",
    "рокет лига": "RocketLeague.exe",
    "рокетлига": "RocketLeague.exe",
    "фоллаут": "Fallout4.exe",
    "фаллаут": "Fallout4.exe",
    "редис": "re2.exe",
    "редиска 2": "re2.exe",
    "хогвартс легаси": "HogwartsLegacy.exe",
    "хогвартс": "HogwartsLegacy.exe",
    "реди дед редемпшн": "RDR2.exe",
    "рдр 2": "RDR2.exe",
    "симс": "TS4.exe",
    "симс 4": "TS4.exe",
    "фар край": "FarCry5.exe",
    "ассасин крид": "AssassinsCreedValhalla.exe",
    "ассасин": "AssassinsCreedValhalla.exe",
    "балдурс гейт": "bg3.exe",
    "балдурс гейт 3": "bg3.exe",
    "сталкер": "Stalker2.exe",
    "сталкер 2": "Stalker2.exe",
    "метро": "MetroExodus.exe",
    "метро исход": "MetroExodus.exe",
    "ворлд оф танкс": "WorldOfTanks.exe",
    "танки": "WorldOfTanks.exe",
    "ворлд оф варшипс": "WorldOfWarships.exe",
    "корабли": "WorldOfWarships.exe",
    "вар тандер": "WarThunder.exe",
    "вартандер": "WarThunder.exe",
    "хертстоун": "Hearthstone.exe",
    "хартстоун": "Hearthstone.exe",
    "средиземье": "ShadowOfWar.exe",
    "длс": "DyingLightGame_x64_rwdi.exe",
    "дайин лайт 2": "DyingLightGame_x64_rwdi.exe",
    "бателфилд": "bf2042.exe",
    "колда": "sp22-cod.exe",
    "колл оф дьюти": "sp22-cod.exe",
    "гта онлаин": "GTA5.exe",
    "осы": "osu!.exe",
    "осу": "osu!.exe",
    "роблокс": "RobloxPlayerBeta.exe",
    "роблакс": "RobloxPlayerBeta.exe",
    "амонг ас": "Among Us.exe",
    "фазмофобия": "Phasmophobia.exe",
    "фазма": "Phasmophobia.exe",
    "террария": "Terraria.exe",
    "факторио": "factorio.exe",
    "сабнатика": "Subnautica.exe",
    "хеллдайверс": "helldivers2.exe",
    "хеллдайверс 2": "helldivers2.exe",
    "римворлд": "RimWorldWin64.exe",
    "но манс скай": "NoMansSky.exe",
    "рейнбоу сикс": "RainbowSix.exe",
    "радуга": "RainbowSix.exe",
    "деад бай дейлайт": "DeadByDaylight.exe",
    "дбд": "DeadByDaylight.exe",
    "раст": "RustClient.exe",
    "арк": "ShooterGame.exe",
    "арк сурвайвал": "ShooterGame.exe",
    "гта сан андреас": "gta_sa.exe",
    "сан андреас": "gta_sa.exe",
    "гта вайс сити": "gta-vc.exe",
    "вайс сити": "gta-vc.exe",
    "гта 4": "GTAIV.exe",
    "хелло найбор": "HelloNeighbor.exe",
    "поппи плейтайм": "PoppyPlaytime.exe",
    "фнаф": "FiveNightsAtFreddys.exe",
    "5 ночей с фредди": "FiveNightsAtFreddys.exe",
    "хоррор": "notepad.exe",  # Заглушка
    "виндоус пинбол": "pinball.exe",
    "сапер": "Minesweeper.exe",
    "косынка": "solitaire.exe",
    "змейка": "snake.exe",
    "тетрис": "tetris.exe",
    
    # === Проигрыватели ===
    "плеер": "wmplayer.exe",
    "виндоус медиа плеер": "wmplayer.exe",
    "видеоплеер": "wmplayer.exe",
    "вилс": "vlc.exe",
    "влс": "vlc.exe",
    "вилс медиа плеер": "vlc.exe",
    "гому": "GOM.exe",
    "гому плеер": "GOM.exe",
    "км плеер": "KMPlayer.exe",
    "кмплеер": "KMPlayer.exe",
    "пот плеер": "PotPlayerMini64.exe",
    "потплеер": "PotPlayerMini64.exe",
    
    # === Архиваторы ===
    "винрар": "WinRAR.exe",
    "архиватор": "WinRAR.exe",
    "7 зип": "7zFM.exe",
    "зип": "7zFM.exe",
    
    # === Антивирусы ===
    "касперский": "avp.exe",
    "антивирус": "avp.exe",
    "доктор веб": "drweb32w.exe",
    "аваст": "AvastUI.exe",

    # === Игры (Steam на D:) ===
    # === Игры Steam на A: ===
    "дота": "A:\\SteamLibrary\\steamapps\\common\\dota 2 beta\\game\\bin\\win64\\dota2.exe",
    "дота 2": "A:\\SteamLibrary\\steamapps\\common\\dota 2 beta\\game\\bin\\win64\\dota2.exe",
    "dota": "A:\\SteamLibrary\\steamapps\\common\\dota 2 beta\\game\\bin\\win64\\dota2.exe",
    "дотка": "A:\\SteamLibrary\\steamapps\\common\\dota 2 beta\\game\\bin\\win64\\dota2.exe",
    "доту": "A:\\SteamLibrary\\steamapps\\common\\dota 2 beta\\game\\bin\\win64\\dota2.exe",
    "доты": "A:\\SteamLibrary\\steamapps\\common\\dota 2 beta\\game\\bin\\win64\\dota2.exe",
    "пабг": "D:\\SteamLibrary\\steamapps\\common\\PUBG\\TslGame\\Binaries\\Win64\\TslGame.exe",
    "pubg": "D:\\SteamLibrary\\steamapps\\common\\PUBG\\TslGame\\Binaries\\Win64\\TslGame.exe",
    "раст": "D:\\SteamLibrary\\steamapps\\common\\Rust\\RustClient.exe",
    "rust": "D:\\SteamLibrary\\steamapps\\common\\Rust\\RustClient.exe",
    "террария": "D:\\SteamLibrary\\steamapps\\common\\Terraria\\Terraria.exe",
    "terraria": "D:\\SteamLibrary\\steamapps\\common\\Terraria\\Terraria.exe",
    "тмод": "D:\\SteamLibrary\\steamapps\\common\\tModLoader\\tModLoader.exe",
    "tmodloader": "D:\\SteamLibrary\\steamapps\\common\\tModLoader\\tModLoader.exe",
    "стим": "C:\\Program Files (x86)\\Steam\\Steam.exe",
    "steam": "C:\\Program Files (x86)\\Steam\\Steam.exe",
    "террарию": "D:\\SteamLibrary\\steamapps\\common\\Terraria\\Terraria.exe",
    "террарии": "D:\\SteamLibrary\\steamapps\\common\\Terraria\\Terraria.exe",
    "доту": "D:\\SteamLibrary\\steamapps\\common\\dota 2 beta\\game\\bin\\win64\\dota2.exe",
    "доты": "D:\\SteamLibrary\\steamapps\\common\\dota 2 beta\\game\\bin\\win64\\dota2.exe",
    "раст": "D:\\SteamLibrary\\steamapps\\common\\Rust\\RustClient.exe",
    "раста": "D:\\SteamLibrary\\steamapps\\common\\Rust\\RustClient.exe",

    
    # === Другие утилиты ===
    "торрент": "utorrent.exe",
    "юторрент": "utorrent.exe",
    "битторрент": "bittorrent.exe",
    "даунлоад мастер": "dmaster.exe",
    "сиклеанер": "CCleaner64.exe",
    "клинер": "CCleaner64.exe",
    "даемон тулс": "DTAgent.exe",
    "ультраисо": "UltraISO.exe",
    "руфус": "rufus.exe",
    "хвинфо": "HWiNFO64.exe",
    "афтербернер": "MSIAfterburner.exe",
    "мси афтербернер": "MSIAfterburner.exe",
    "гпу зет": "GPU-Z.exe",
    "спидифан": "SpeedFan.exe",
    "нотепад плюс плюс": "notepad++.exe",
    "тайпера": "Typora.exe",
    "обсидиан": "Obsidian.exe",
    "ноушен": "Notion.exe",
    "анидеск": "AnyDesk.exe",
    "тимвьюер": "TeamViewer.exe",
    "радмин": "radmin.exe",
    "дискорд": "Discord.exe",
    "спотифай": "Spotify.exe",
    "споти": "Spotify.exe",
    "яндекс музыка": "YandexMusic.exe",
    "я музыка": "YandexMusic.exe",
    "я музыка": "YandexMusic.exe",
    "итюнс": "iTunes.exe",
    "айтюнс": "iTunes.exe",
    "эппл мьюзик": "iTunes.exe",
    "офис": "WINWORD.EXE",
    "ворд эксель": "EXCEL.EXE",
    "пайтон": "python.exe",
    "питон": "python.exe",
    "нода": "node.exe",
    "джава": "java.exe",
    "ява": "java.exe",
    
    # === Магазины приложений ===
    "майкрософт стор": "ms-windows-store:",
    "магазин приложений": "ms-windows-store:",
    "микрософт стор": "ms-windows-store:",
}

# ========== САЙТЫ ==========
SITES = {
    "ютуб музыка": "https://music.youtube.com",
    "ютуб шортс": "https://youtube.com/shorts",
    "ютуб": "https://youtube.com",
    "гугл документы": "https://docs.google.com",
    "гугл таблицы": "https://sheets.google.com",
    "гугл диск": "https://drive.google.com",
    "гугл карты": "https://maps.google.com",
    "гугл": "https://google.com",
    "яндекс карты": "https://maps.yandex.ru",
    "яндекс музыка": "https://music.yandex.ru",
    "яндекс маркет": "https://market.yandex.ru",
    "яндекс": "https://ya.ru",
    "гитхаб": "https://github.com",
    "википедия": "https://wikipedia.org",
    "вк": "https://vk.com",
    "телеграм веб": "https://web.telegram.org",
    "вотсап веб": "https://web.whatsapp.com",
    "почта": "https://mail.google.com",
    "джимейл": "https://mail.google.com",
    "переводчик": "https://translate.google.com",
    "авито": "https://avito.ru",
    "озон": "https://ozon.ru",
    "вайлдберриз": "https://wildberries.ru",
    "ютреб": "https://youtrack.ru",
    "хабр": "https://habr.com",
    "пикабу": "https://pikabu.ru",
    "реддит": "https://reddit.com",
    "твич": "https://twitch.tv",
    "нетфликс": "https://netflix.com",
    "кинопоиск": "https://kinopoisk.ru",
    "окко": "https://okko.tv",
    "иви": "https://ivi.ru",
    "вк видео": "https://vk.com/video",
    "рутуб": "https://rutube.ru",
    "дзен": "https://dzen.ru",
    "лента новостей": "https://lenta.ru",
    "риа новости": "https://ria.ru",
    "спорт ру": "https://sport.ru",
    "спортс": "https://sports.ru",
    "ютуб": "https://youtube.com",
    "youtube": "https://youtube.com",
    "ютюб": "https://youtube.com",
    "гугл": "https://google.com",
    "google": "https://google.com",
    "вики": "https://wikipedia.org",
    "википедия": "https://wikipedia.org",
    "википедию": "https://wikipedia.org",
    "википедии": "https://wikipedia.org",
    "вк": "https://vk.com",
    "вконтакте": "https://vk.com",
    "телеграм": "https://web.telegram.org",
    "телегу": "https://web.telegram.org",
    "почта": "https://mail.google.com",
    "почту": "https://mail.google.com",
    "переводчик": "https://translate.google.com",
    "яндекс": "https://ya.ru",
    "яндекса": "https://ya.ru",

}

# ========== ПРОЦЕССЫ ДЛЯ ЗАКРЫТИЯ ==========
PROCESS_MAP = {
    "блокнот": "notepad.exe",
    "калькулятор": "calculator.exe",
    "браузер": "msedge.exe",
    "проводник": "explorer.exe",
    "паинт": "mspaint.exe",
    "tlauncher": "java.exe",
    "тлаунчер": "java.exe",
    "tla": "java.exe",
    "obs": "obs64.exe",
    "obs studio": "obs64.exe",
    "стим": "steam.exe",
    "steam": "steam.exe",
    "дискорд": "discord.exe",
    "discord": "discord.exe",
    "телеграм": "telegram.exe",
    "telegram": "telegram.exe",
    "вайбер": "viber.exe",
    "viber": "viber.exe",
    "эпик": "EpicGamesLauncher.exe",
    "epic": "EpicGamesLauncher.exe",
    "дота": "dota2.exe",
    "дота 2": "dota2.exe",
    "dota": "dota2.exe",
    "террария": "Terraria.exe",
    "террарию": "Terraria.exe",
    "terraria": "Terraria.exe",
    "доту": "dota2.exe",
    "доты": "dota2.exe",
}

# ========== МУЗЫКАЛЬНЫЕ ПЛЕЙЛИСТЫ (заготовка) ==========
MUSIC_PLAYLISTS = {
    "спокойная": "lofi hip hop chill",
    "энергичная": "workout motivation music",
    "классика": "classical music mozart",
    "джаз": "jazz instrumental",
    "рок": "rock music hits",
    "поп": "pop music hits",
    "электронная": "electronic music mix",
}

# ========== ГОРОД ПО УМОЛЧАНИЮ ==========
DEFAULT_CITY = "Moscow"